---
layout: post
title: "A Basic Logical Invest Global Market Rotation Strategy"
date: "May 18, 2015"
---
```{r global_options, include=FALSE}

library(knitr)
opts_chunk$set(tidy=FALSE, size='scriptsize',
               fig.align='center',  fig.width=7,  fig.height=5,
               message=FALSE,warning=FALSE, fig.path=paste0(VAR, 'public/images/2015-05-18-Rotation_Strategy/'))
options(width=81,continue=" ",digits=8)
```

Here's the strategy: take five global market ETFs (MDY, ILF, FEZ, EEM, and EPP), along with a treasury ETF (TLT), and every month, fully invest in the security that had the best momentum. While I've tried various other tweaks, none have given the intended high return performance that the original variant has.

```{r echo=F}
require(quantmod)
require(PerformanceAnalytics)
```

```{r results='hide'}

symbols <- c("MDY", "TLT", "EEM", "ILF", "EPP", "FEZ")
getSymbols(symbols, from="1990-01-01")
prices <- list()
for(i in 1:length(symbols)) {
  prices[[i]] <- Ad(get(symbols[i]))
}
# Get data and use adjusted prices

prices <- do.call(cbind, prices)
colnames(prices) <- gsub("\\.[A-z]*", "", colnames(prices))
returns <- Return.calculate(prices)
returns <- na.omit(returns)
# Format data

logicInvestGMR <- function(returns, lookback = 3) {
  ep <- endpoints(returns, on = "months") 
  # endpoints on months
  weights <- list()
  # Create a list for the weights
  for(i in 2:(length(ep) - lookback)) # For all periods that can be calculated
  {
    retSubset <- returns[ep[i]:ep[i+lookback],]
    # Get returns within the time period
    cumRets <- Return.cumulative(retSubset)
    # Get cumulative return of time period
    rankCum <- rank(cumRets)
    # Rank the cumulative returns for each ETF
    weight <- rep(0, ncol(retSubset))
    # Set up weights to all be initially 0
    weight[which.max(cumRets)] <- 1
    # Whichever one has the highest cumulative return gets all the weight
    weight <- xts(t(weight), order.by=index(last(retSubset)))
    weights[[i]] <- weight
    # Create weight for time period
  }
  weights <- do.call(rbind, weights)
  # combine all the weights together
  stratRets <- Return.portfolio(R = returns, weights = weights)
  # Calculate portfolio return
  return(stratRets)
}

gmr <- logicInvestGMR(returns)

```

And here's the performance:

```{r}

kable(round(rbind(table.AnnualizedReturns(gmr), maxDrawdown(gmr), CalmarRatio(gmr)),4))

```

With the resultant equity curve:

```{r}
charts.PerformanceSummary(gmr)

```

